### ISSUE TITLE
How to compute the mlc score?

### ISSUE THREAD

**Issue by Fan-Jian-Zheng** [zhjohnchan/R2GenCMN#1]
Thanks for your work and sharing the code.
I see the paper compute the mlc score about the mimic_cxr dataset,
so how do we compute the mlc score？

**Comment by zhjohnchan** [comment]
Hello Fanjian @Fan-Jian-Zheng,

Thanks for your attention!

You can use either [chestpert](https://github.com/MIT-LCP/mimic-cxr/tree/master/txt/chexpert) or [chexbert](https://github.com/stanfordmlgroup/CheXbert) to obtain the disease labels of the generated and reference reports and then compute the P, R, and F scores.

Best,
Zhihong

**Comment by JoshSmith0118** [comment]
> Thanks for your work and sharing the code. I see the paper compute the mlc score about the mimic_cxr dataset, so how do we compute the mlc score？
hi bro, have you run this code successfully, I am wondering could you leave an email or other contact ways? I have some questions for you, thx again.

**Comment by dzldzldzl** [comment]
Thanks for your work and sharing the code. I see the paper compute the mlc score about the mimic_cxr dataset, so how do we compute the mlc score？
hi bro, have you run this code successfully, I am wondering could you leave an email or other contact ways? I have some questions for you, thx again.

**Comment by catfish132** [comment]
> 
which mode did you used?  I found three mode to calculate P R and F scores, which is 'mention'/'negation/'uncertain'. It is not explained in all of your relevant paper, GitHub repository, and why?

**Comment by zhjohnchan** [comment]
Hi all,

Thanks for your attention! I wrote an example code to compute the score [here](https://github.com/zhjohnchan/R2GenCMN/blob/main/compute_ce.py).

Best,
Zhihong
