### ISSUE TITLE
The annotation.json file for MIMIC

### ISSUE THREAD

**Issue by xiat0616** [zhjohnchan/R2GenCMN#10]
Hi @zhjohnchan,
Great work. I am wondering if you can share the annotation.json file for the MIMIC dataset? Or the code to produce it? Thank you so much.

Best,
Tian

**Comment by zhjohnchan** [comment]
Hi @xiat0616,

Thanks for your attention!

You can apply the dataset [here](https://drive.google.com/file/d/1DS6NYirOXQf8qYieSVMvqNwuOlgAbM_E/view?usp=sharing) with your license of [PhysioNet](https://physionet.org/content/mimic-cxr-jpg/2.0.0/).

Best,
Zhihong
