### ISSUE TITLE
Macro vs Micro vs Example-based F1

### ISSUE THREAD

**Issue by ChantalMP** [zhjohnchan/R2GenCMN#12]
Hi,

are the scores reported in this paper macro, micro or example-based F1 scores? 

Thanks a lot in advance!

Best regards,

Chantal

**Comment by zhjohnchan** [comment]
Hi @ChantalMP ,

Thanks for your attention! It's the macro-based score.

All the best,
Zhihong

**Comment by ChantalMP** [comment]
Thanks!
