### ISSUE TITLE
关于mlc_score的计算

### ISSUE THREAD

**Issue by lllsy12138** [zhjohnchan/R2GenCMN#4]
使用cheXbert得到的csv中有一些label值为空，读入时会变成NaN，请问作者是怎么处理这些为空（没有标注为1，0或-1）的值？
如果都赋值为同一常数，会不会出现precision过高的情况？
非常感谢！
![image](https://user-images.githubusercontent.com/50816213/181026908-92692b57-0798-4107-9742-dfbaa87d5f00.png)

**Comment by wlufy** [comment]
同问

**Comment by Xjmengnieer** [comment]
所以，这个问题解决了吗请问

**Comment by Otiss-pang** [comment]
同问++

**Comment by zhjohnchan** [comment]
Hi all,

Thanks for your attention to our paper! I wrote an example code to compute the score [here](https://github.com/zhjohnchan/R2GenCMN/blob/main/compute_ce.py).

Best,
Zhihong
