### ISSUE TITLE
About report_masks?

### ISSUE THREAD

**Issue by caodoanh2001** [zhjohnchan/R2GenCMN#5]
Hello,

Thank you for your good work.
However, I saw that you use the key "report_masks" from annotation dictionary, but it is not included in file "annotation.json" you provided.
Even you used "report_masks" to compute loss function, you have no explanation for this.

Hope receive your response soon,
Best.

**Comment by dengyi-g** [comment]
report_masks are defined here: 
https://github.com/zhjohnchan/R2GenCMN/blob/3a995dc7744222187c0a927e8b44a555191bf592/modules/datasets.py#L19-L21
then
https://github.com/zhjohnchan/R2GenCMN/blob/3a995dc7744222187c0a927e8b44a555191bf592/modules/datasets.py#L55-L57

**Comment by zhjohnchan** [comment]
Hi @douseful and @caodoanh2001,

Thank you so much for the explanation @douseful!

Best,
Zhihong
