### ISSUE TITLE
Why do we take the first channel feature map of image features when inferring？

### ISSUE THREAD

**Issue by Xjmengnieer** [zhjohnchan/R2GenCMN#6]
As shown in the title, the code is as follows：
![image](https://user-images.githubusercontent.com/88227513/204526376-0e34cbd2-4dd3-48a5-8155-e1374c94ab13.png)

could you give me some advice ? Thanks

**Comment by zhjohnchan** [comment]
Hi @Xjmengnieer,

Thanks for your attention! It doesn't mean the first channel of the features. It just reshapes the tensors.

Best,
Zhihong
