### ISSUE TITLE
IU X-Ray提供的权重和模型的对齐问题

### ISSUE THREAD

**Issue by Liqq1** [zhjohnchan/R2GenCMN#8]
权重文件为Readme中下载的`model_iu_xray.pth`
运行`bash test_iu_xray.sh`
会有以下报错：
```
size mismatch for encoder_decoder.logit.weight: copying a param with shape torch.Size([761, 512]) from checkpoint, the shape in current model is torch.Size([760, 512]).
```
同时还出现大量的Missing key(s) in state_dict

**Comment by douseful** [comment]
你应该是改动了 threshold 这个参数，这会导致最终的词典总长度和提供的模型参数不一样

**Comment by zhjohnchan** [comment]
Hi @Liqq1,

Thanks for your attention! Please check if the checkpoint is downloaded correctly.

Best,
Zhihong
